[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Chris Heller <hellertime@gmail.com>"]

[dependencies]
crossbeam = "0.2.8"
num = "0.1.27"
image = "0.13.0"
iron = "0.5.1"
logger = "0.4.0"
env_logger = "0.5.13"
mime = "0.2.3"
router = "0.5.1"
urlencoded = "0.5.0"
